### ISSUE TITLE
Unable to Query users with Get-OktaUser

### ISSUE THREAD

**Issue by creamers** [okta/oktasdk-csharp#12]
```
Connect-Okta -Token $APIKey -FullDomain 'https://myorg.okta.com'
Get-OktaUser firstnamelastname@domain.tld
```

The error code is Get-OktaUser : Method not found: 'Okta.Core.EnumerableResults`1<!0> Okta.Core.Clients.ApiClient`1.GetFilteredEnumerator(Okta.Core.FilterBuilder, Int32, System.String, System.String, System.Nullable`1<System.DateTime>)'.

Windows 10
Okta.Core.Automation 0.1.0.2 [Approved]

 With the full error being
```
PSMessageDetails      : 
Exception             : System.MissingMethodException: Method not found: 'Okta.Core.EnumerableResults`1<!0> Okta.Core.Clients.ApiClient`1.GetFilteredEnumerator(Okta.Core.FilterBuilder, Int32, System.String, System.String, 
                        System.Nullable`1<System.DateTime>)'.
                           at Okta.Core.Automation.GetOktaUser.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Get-OktaUser], MissingMethodException
FullyQualifiedErrorId : System.MissingMethodException,Okta.Core.Automation.GetOktaUser
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 3
PipelineIterationInfo : {}
```

**Comment by raphaellondner-okta** [comment]
This issue has been resolved with the latest version of the Okta PowerShell Module (v0.1.5.6) cf. https://chocolatey.org/packages/Okta.Core.Automation/0.1.5.6
