### ISSUE TITLE
Newtonsoft.json dependency issues

### ISSUE THREAD

**Issue by thnk2wn** [okta/oktasdk-csharp#13]
You guys might consider using ILMERGE to get rid of dependency issues on Newtonsoft.json - and/or have the package deal with assembly binding redirects or require latest json.net?

This is a popular library many people reference and the dependency tends to cause mismatch issues. In my case I had a unit test project that had no reference to Newtonsoft.Json. That project referenced another project (to be tested) that referenced a 9.0.0.1 version of Newtonsoft.Json. By default I think installing Okta.Core.Client nuget package installed the lowest compatible version of Json.net. I ended up having to manually add an assembly binding redirect and then uninstalling Okata.Core.Client, install the latest version of Newtonsoft.Json into the unit test project, then re-install Okata.Core.Client.

> 
System.TypeInitializationException : The type initializer for 'Okta.Core.Constants' threw an exception.
  ----> System.TypeInitializationException : The type initializer for 'Okta.Core.Utils' threw an exception.
  ----> System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Okta.Core.Constants.get_UserAgent()
   at Okta.Core.OktaSettings..ctor()
   at Okta.Core.Clients.AuthenticatedClient..ctor(String apiToken, String subdomain)
   at Okta.Core.Clients.OktaClient..ctor(String apiToken, String subdomain)
   at Hakata.Web.Services.Security.MFA.MultiFactorAuthService..ctor(String apiToken, String appSubdomain) in C:\Source2013\Cyrus\Cyrus3\tools\TwoFactorAuthDisco\B-10014-C3-OKTA\Hakata.Web\Services\Security\MFA\IMultiFactorAuthService.cs:line 29
   at Hakata.Test.Integration.Security.MultiFactorAuthTests.CreateService() in C:\Source2013\Cyrus\Cyrus3\tools\TwoFactorAuthDisco\B-10014-C3-OKTA\Hakata.Test.Integration\Security\MultiFactorAuthTests.cs:line 23
   at Hakata.Test.Integration.Security.MultiFactorAuthTests.Previously_Enrolled_User_Has_Sms_Factor() in C:\Source2013\Cyrus\Cyrus3\tools\TwoFactorAuthDisco\B-10014-C3-OKTA\Hakata.Test.Integration\Security\MultiFactorAuthTests.cs:line 13
--TypeInitializationException
   at Okta.Core.Utils.GetAssemblyVersion()
   at Okta.Core.Constants..cctor()
--FileLoadException
   at Okta.Core.Utils..cctor()

**Comment by thnk2wn** [comment]
Meant to mention I'm using version 0.3.0.0 of the NuGet package

**Comment by raphaellondner-okta** [comment]
Hi Geoff, thanks a lot for raising this issue, which was completely an error on our part. We've fixed this dependency issue in our latest release ([v0.3.0.1](https://www.nuget.org/packages/Okta.Core.Client/0.3.0.1)) so please test it and don't hesitate to let us know if you still have any issue. Thank you!
